[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"

solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

gas_reports = ["Pocket", "PocketController"]
[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"

